// Word list: all 5-letter words starting with J
// These are the valid guesses AND the answer pool
const J_WORDS = [
  "JABOT","JACAL","JACET","JACKS","JACKY","JADED","JADES","JAFIS","JAGAS","JAGGS",
  "JAGGY","JAGIR","JAGRA","JAIIS","JAILS","JAKES","JALAP","JALOP","JAMBE","JAMBO",
  "JAMBS","JAMBK","JAMES","JAMMY","JAMPS","JANES","JANNS","JANTY","JAPAN","JAPED",
  "JAPER","JAPES","JARKS","JARLS","JARMA","JARPS","JARTA","JASPE","JASPS","JATKI",
  "JATOS","JATTS","JAUKS","JAUNTS","JAVA","JAVEL","JAVAS","JAWAN","JAWED","JAWER",
  "JAWNS","JAXIE","JAZZY","JEANS","JEBEL","JEDED","JEDEL","JEEES","JEELS","JEELY",
  "JEERS","JEFES","JEHAD","JEHUS","JELED","JELLO","JELLS","JELLY","JEMBE","JEMMY",
  "JENNY","JEONS","JERRS","JERTH","JESSE","JESTS","JETAN","JETED","JETER","JETES",
  "JETON","JETTY","JEUHS","JEWEL","JEWIE","JEZES","JIBBA","JIBBS","JIBED","JIBER",
  "JIBES","JIFFS","JIFFY","JIGOT","JIGSA","JIGSAW","JILTS","JIMMY","JIMPY","JINNE",
  "JINNI","JINNS","JINXED","JINXES","JIPES","JIRO","JIRGA","JIRRE","JISM","JITNEY",
  "JIVEY","JIVOS","JIZZY","JOANN","JOBS","JOBED","JOBES","JOCAST","JOCKO","JOCKS",
  "JOCKY","JOCOS","JOEYS","JOHNS","JOINED","JOINS","JOINT","JOIST","JOKED","JOKER",
  "JOKES","JOKEY","JOLLY","JOLTS","JOLTY","JOMON","JONAH","JONAS","JONES","JONGS",
  "JONTA","JOOKS","JORDS","JOSES","JOSHY","JOSIA","JOSIE","JOTAS","JOTTY","JOUST",
  "JOWED","JOWLS","JOWLY","JOYED","JOYFS","JUBAS","JUBES","JUCOS","JUDAS","JUDGE",
  "JUDGY","JUDOS","JUGAL","JUGGS","JUGGY","JUGUM","JUICE","JUICY","JUMAR","JUMBO",
  "JUMBY","JUMPS","JUMPY","JUNC","JUNCO","JUNKS","JUNKY","JUNTA","JUNTI","JUPES",
  "JUPON","JURAT","JUROR","JURY","JUSTE","JUSTO","JUTES","JUTTY","JUVES","JUVIE"
];

// Filter to only valid 5-letter words (safety)
const VALID_WORDS = J_WORDS.filter(w => w.length === 5);

// Answer pool - curated common/recognizable J-words
const ANSWER_POOL = [
  "JACKS","JACKY","JADED","JADES","JAILS","JAKES","JAMBE","JAMBO","JAMMY","JAPAN",
  "JAPED","JAPER","JAPES","JAWAN","JAWED","JAZZY","JEANS","JEERS","JELLY","JEMMY",
  "JENNY","JESTS","JETTY","JEWEL","JIBED","JIBER","JIBES","JIFFY","JIMMY","JINNI",
  "JINNS","JOCKS","JOEYS","JOHNS","JOINS","JOINT","JOIST","JOKED","JOKER","JOKES",
  "JOKEY","JOLLY","JOLTS","JORDS","JOUST","JOWLS","JOWLY","JOYED","JUDGE","JUDOS",
  "JUICE","JUICY","JUMBO","JUMPS","JUMPY","JUNCO","JUNKS","JUNKY","JUNTA","JUPES",
  "JURAT","JUROR","JUTES","JUVIE","JABOT","JAGGY","JAILS","JALAP","JAMBS","JANES",
  "JAPER","JAWED","JEANS","JEBEL","JEELS","JEFES","JEHAD","JELLO","JELLS","JENNY",
  "JETON","JETTY","JIBBA","JIBBS","JIBED","JIFFS","JIFFY","JIMMY","JINNI","JINNS",
  "JIVED","JIVES","JOCKO","JOCKS","JOGGS","JOINED","JOINT","JOIST","JOKED","JOKER",
  "JOLLY","JOLTS","JOUST","JOWLS","JOYED","JUBAS","JUDGE","JUGAL","JUICE","JUICY",
  "JUMAR","JUMBO","JUMPS","JUMPY","JUNCO","JUNKS","JUNKY","JUNTA","JUROR","JUTES"
];

// Remove duplicates from answer pool
const UNIQUE_ANSWERS = [...new Set(ANSWER_POOL.filter(w => w.length === 5))];

// Seeded random based on date string
function getDailyWord(dateStr) {
  if (!dateStr) {
    const d = new Date();
    dateStr = d.getFullYear() + '-' + (d.getMonth()+1) + '-' + d.getDate();
  }
  let hash = 0;
  for (let i = 0; i < dateStr.length; i++) {
    const ch = dateStr.charCodeAt(i);
    hash = ((hash << 5) - hash) + ch;
    hash |= 0;
  }
  const idx = Math.abs(hash) % UNIQUE_ANSWERS.length;
  return UNIQUE_ANSWERS[idx];
}

// Valid guesses: any 5-letter word starting with J
// We use the full VALID_WORDS list plus common English 5-letter J-words
const GUESS_POOL = [...new Set([
  ...VALID_WORDS,
  "JACKY","JADED","JAZZY","JELLY","JIMMY","JOKEY","JOKER","JOLLY","JUMBO","JUMPY",
  "JUNKY","JURY","JUSTO","JINXED","JOCKO","JAMMY","JAWED","JEWEL","JOINT","JOUST",
  "JUDGE","JUICE","JUICY","JUNTA","JUROR","JUTES","JACKS","JAILS","JEANS","JEERS",
  "JIBED","JIBES","JIFFY","JINNI","JINNS","JOCKS","JOGGS","JOINS","JOIST","JOKED",
  "JOKES","JOLTS","JOWLS","JOWLY","JOYED","JUMPS","JUNCO","JUNKS","JUPES","JUVIE",
  "JAMBO","JAMBS","JAWAN","JAPAN","JAPER","JAPES","JAWED","JAZZY","JEBEL","JELLO",
  "JEMMY","JENNY","JESTS","JETON","JETTY","JIBBA","JIBBS","JIFFS","JIFFY","JIVED",
  "JIVES","JIVOS","JOEYS","JOHNS","JORDS","JOSES","JOTTY","JUBAS","JUDOS","JUGAL",
  "JUGGS","JUGGY","JUGUM","JUMAR","JUMPS","JUMPY","JUNCO","JUNKS","JUNKY","JUNTA",
  "JUPON","JURAT","JUTES","JUTTY","JUVES","JUVIE","JINXES","JOCKY","JOGGED","JOINER",
  "JOINTS","JOISTS","JOKING","JOLLIES","JOSTLE","JOTTED","JOTTES","JOVIAL","JOWING",
  "JUDGED","JUDGES","JUGGLE","JUMPED","JUMPER","JUMPS","JUNKED","JUNKET","JURIES",
  "JUSTLY","JUTTED","JUVIES","JABOTS","JAGGIES","JAILOR","JALAPS","JAMBING","JANITOR",
  "JAPING","JAPINGS","JARKED","JARINA","JARKING","JARL","JAROOL","JARS","JASPER",
  "JASPES","JATO","JATOS","JAUNCE","JAUNTED","JAUNTIER","JAUNTS","JAUP","JAUPED",
  "JAUPING","JAUPS","JAUSED","JAUSING","JAVAS","JAVEL","JAVELIN","JAWAN","JAWANS",
  "JAWBONE","JAWED","JAWING","JAWLESS","JAWLIKE","JAWLINE","JAWS","JAYBIRD","JAYWALK",
  "JAYWALKED","JAYWALKS","JAZZIER","JAZZILY","JAZZING","JAZZMAN","JAZZMEN","JAZZY",
  "JEALOUS","JEALOUSY","JEAN","JEANS","JEBEL","JEDIS","JEER","JEERED","JEERER",
  "JEERERS","JEERING","JEERINGLY","JEERS","JEEZ","JEFES","JEHAD","JEHADS","JEHUS",
  "JELLED","JELLIES","JELLING","JELLO","JELLOS","JELLY","JELLYBEAN","JELLYFISH",
  "JEMBE","JEMBES","JEMMY","JENNET","JENNETS","JENNIES","JENNY","JEONS","JERRY",
  "JERSEY","JERSEYS","JESSED","JESSES","JEST","JESTED","JESTER","JESTERS","JESTING",
  "JESTS","JESUIT","JESUITS","JET","JETBONE","JETED","JETER","JETES","JETLAG",
  "JETLINER","JETON","JETONS","JETPORT","JETS","JETTED","JETTER","JETTERS","JETTIES",
  "JETTING","JETTY","JETTYS","JEUNES","JEWEL","JEWELED","JEWELER","JEWELERS","JEWELRY",
  "JEWELS","JEWIE","JIB","JIBBA","JIBBAS","JIBBED","JIBBER","JIBBERS","JIBBING",
  "JIBBS","JIBED","JIBER","JIBERS","JIBES","JIBING","JIFF","JIFFS","JIFFY","JIG",
  "JIGABOO","JIGGED","JIGGING","JIGGS","JIGGY","JIGJOG","JIGJOGGED","JIGSAW",
  "JIGSAWED","JIGSAWS","JIHAD","JIHADS","JILTED","JILTER","JILTERS","JILTS","JIMMY",
  "JIMMIED","JIMMIES","JIMMYING","JIMP","JIMPER","JIMPLE","JIMPS","JIN","JINGAL",
  "JINGALL","JINGKO","JINGLED","JINGLER","JINGLERS","JINGLES","JINGLING","JINKS",
  "JINN","JINNI","JINNIS","JINNS","JINX","JINXED","JINXES","JINXING","JIP","JIPE",
  "JIPES","JIPING","JIROS","JIRRAS","JISM","JISMS","JITNEY","JITNEYS","JIVE",
  "JIVED","JIVER","JIVERS","JIVES","JIVEST","JIVIN","JIVING","JIVVY","JIZZ",
  "JIZZED","JIZZING","JOAN","JOB","JOBBED","JOBBERS","JOBBING","JOBED","JOBEY",
  "JOBES","JOBS","JOCASTA","JOCK","JOCKEY","JOCKEYED","JOCKEYING","JOCKEYS","JOCKO",
  "JOCKOS","JOCKS","JOCOS","JODHPUR","JODHPURS","JOEYS","JOEY","JOG","JOGGED",
  "JOGGER","JOGGERS","JOGGING","JOGGINGS","JOGS","JOINED","JOINER","JOINERS",
  "JOINING","JOINS","JOINT","JOINTED","JOINTER","JOINTERS","JOINTING","JOINTLY",
  "JOINTS","JOIST","JOISTED","JOISTER","JOISTERS","JOISTING","JOISTS","JOKED",
  "JOKER","JOKERS","JOKES","JOKEY","JOKIER","JOKILY","JOKING","JOKINGLY","JOLLIES",
  "JOLLY","JOLTED","JOLTER","JOLTERS","JOLTING","JOLTS","JOLTY","JOMON","JONAH",
  "JONAH","JONAS","JONES","JONGS","JONTA","JOOKS","JORAM","JORGE","JORDS","JOSEF",
  "JOSEPH","JOSES","JOSH","JOSHED","JOSHER","JOSHERS","JOSHES","JOSHING","JOSHY",
  "JOSIA","JOSIE","JOT","JOTA","JOTAS","JOTS","JOTTA","JOTTY","JOTTED","JOTTER",
  "JOTTING","JOUAL","JOUK","JOUKED","JOUKS","JOULE","JOULES","JOUR","JOURNO",
  "JOURNAL","JOURNEY","JOUST","JOUSTED","JOUSTER","JOUSTING","JOUSTS","JOW","JOWED",
  "JOWING","JOWL","JOWLED","JOWLER","JOWLIER","JOWLS","JOWLY","JOWS","JOY","JOYED",
  "JOYFUL","JOYFULLER","JOYFULNESS","JOYING","JOYLESS","JOYOUS","JOYPOPS","JOYS",
  "JOYRIDE","JOYRIDES","JOYRIDER","JUBA","JUBAH","JUBAS","JUBB","JUBBA","JUBBAS",
  "JUBBS","JUBEE","JUBES","JUCHU","JUCOS","JUDAS","JUDGE","JUDGED","JUDGEMENT",
  "JUDGES","JUDGING","JUDGMENT","JUDGY","JUDO","JUDOS","JUG","JUGAL","JUGGED",
  "JUGGER","JUGGERNAUT","JUGGINS","JUGGLING","JUGGS","JUGGY","JUGS","JUGUM",
  "JUICE","JUICED","JUICER","JUICERS","JUICES","JUICIER","JUICILY","JUICING",
  "JUICY","JUMAR","JUMARS","JUMBO","JUMBOS","JUMBUCK","JUMBY","JUMEN","JUMP",
  "JUMPED","JUMPER","JUMPERS","JUMPIER","JUMPILY","JUMPING","JUMPS","JUMPY",
  "JUNC","JUNCO","JUNCOS","JUNCTION","JUNK","JUNKED","JUNKET","JUNKETING","JUNKETS",
  "JUNKIE","JUNKIES","JUNKING","JUNKS","JUNKY","JUNTA","JUNTAS","JUNTI","JUPES",
  "JUPON","JUPONS","JURAT","JURATS","JURE","JURIS","JUROR","JURORS","JURY","JUS",
  "JUST","JUSTED","JUSTER","JUSTEST","JUSTICE","JUSTIFY","JUSTING","JUSTLE",
  "JUSTLED","JUSTLES","JUSTLY","JUT","JUTED","JUTES","JUTS","JUTTED","JUTTER",
  "JUTTY","JUVENAL","JUVENILE","JUVES","JUVIE","JUVIES","JUXTA","JUXTAPOSE"
])].filter(w => w.length === 5).sort();
