#!/usr/bin/env python3
"""Pick today's daily Jordle word and write current-word.js."""
import re
import random
import datetime

def main():
    # Read the wordlist.js to extract the ANSWER_POOL words
    with open('wordlist.js', 'r') as f:
        content = f.read()

    # Extract words from ANSWER_POOL array (UNIQUE_ANSWERS is a JS expression,
    # not a literal array, so we can't regex-match it from Python)
    match = re.search(r'ANSWER_POOL\s*=\s*\[([^\]]+)\]', content)
    if not match:
        raise ValueError("Could not find ANSWER_POOL in wordlist.js")

    words_str = match.group(1)
    words = [w.strip().strip('"').strip("'") for w in words_str.split(',') if w.strip()]
    # Replicate the JS: filter to 5-letter words, then deduplicate (like [...new Set()])
    words = list(dict.fromkeys(w for w in words if len(w) == 5))

    if not words:
        raise ValueError("No valid 5-letter J-words found in answer pool")

    # Pick a random word for today
    today = datetime.date.today().isoformat()

    # Seed with today's date so the pick is deterministic for the day
    # but different from the client-side hash (so the Action drives the word)
    random.seed(today + "-jordle-action")
    daily_word = random.choice(words)

    # Write current-word.js
    js_content = f"""// Auto-generated by GitHub Actions - {today}
// This file is updated daily at midnight UTC
const DAILY_WORD_OVERRIDE = "{daily_word}";
const DAILY_WORD_DATE = "{today}";
"""

    with open('current-word.js', 'w') as f:
        f.write(js_content)

    print(f"Daily word for {today}: {daily_word}")

if __name__ == '__main__':
    main()
